from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("notifications/", views.notifications, name="notifications"),
    path("suppliers/", views.supplier_registry, name="supplier_registry"),
    path("company/", views.company_profile, name="company_profile"),
    path("company/documents/upload/", views.upload_supplier_document, name="upload_supplier_document"),
    path("company/application/resubmit/", views.resubmit_application, name="resubmit_application"),
    path("suppliers/<int:application_pk>/", views.supplier_detail, name="supplier_detail"),
    path("supplier-documents/<int:document_pk>/download/", views.supplier_document_download, name="supplier_document_download"),
    path("contracts/", views.contract_registry, name="contract_registry"),
    path("contracts/<int:contract_pk>/<str:status>/", views.update_contract_status, name="update_contract_status"),
    path("protocols/<int:protocol_pk>/", views.protocol_detail, name="protocol_detail"),
    path("exports/tenders.csv", views.tender_export, name="tender_export"),
    path("exports/audit.csv", views.audit_export, name="audit_export"),
    path("audit/", views.audit_registry, name="audit_registry"),
    path("operations/", views.operations_dashboard, name="operations_dashboard"),
    path("imports/<int:source_pk>/run/", views.run_tender_import, name="run_tender_import"),
    path("employees/", views.employee_registry, name="employee_registry"),
    path("employees/invite/", views.invite_employee, name="invite_employee"),
    path("employees/<int:membership_pk>/toggle/", views.toggle_employee, name="toggle_employee"),
    path("organizations/", views.organization_registry, name="organization_registry"),
    path("organizations/new/", views.organization_create, name="organization_create"),
    path("organizations/<int:organization_pk>/employees/", views.employee_registry, name="organization_employees"),
    path("tender-templates/", views.tender_template_registry, name="tender_template_registry"),
    path("tender-templates/<int:template_pk>/create/", views.tender_create_from_template, name="tender_create_from_template"),
    path("health/", views.health, name="health"),
    path("tenders/", views.tender_list, name="tender_list"),
    path("tenders/new/", views.tender_create, name="tender_create"),
    path("tenders/<int:pk>/edit/", views.tender_edit, name="tender_edit"),
    path("tenders/<int:pk>/cancel/", views.tender_cancel, name="tender_cancel"),
    path("tenders/<int:pk>/copy/", views.tender_copy, name="tender_copy"),
    path("tenders/<int:pk>/save-template/", views.tender_save_template, name="tender_save_template"),
    path("tenders/<int:pk>/comparison/", views.tender_comparison, name="tender_comparison"),
    path("tenders/<int:tender_pk>/external-documents/<int:document_index>/", views.external_document_redirect, name="external_document_redirect"),
    path("tenders/<int:pk>/", views.tender_detail, name="tender_detail"),
    path("tenders/<int:pk>/bid/", views.bid_submit, name="bid_submit"),
    path("tenders/<int:pk>/favorite/", views.toggle_favorite, name="toggle_favorite"),
    path("tenders/<int:pk>/question/", views.ask_question, name="ask_question"),
    path("tenders/<int:pk>/lot/", views.add_lot, name="add_lot"),
    path("tenders/<int:pk>/document/", views.add_document, name="add_document"),
    path("questions/<int:question_pk>/answer/", views.answer_question, name="answer_question"),
    path("suppliers/<int:application_pk>/<str:decision>/", views.review_supplier, name="review_supplier"),
    path("approvals/<int:approval_pk>/<str:decision>/", views.review_tender, name="review_tender"),
    path("documents/<int:document_pk>/download/", views.document_download, name="document_download"),
    path("tenders/<int:tender_pk>/winner/<int:bid_pk>/", views.select_winner, name="select_winner"),
    path("tenders/<int:tender_pk>/winner/<int:bid_pk>/remove/", views.unselect_winner, name="unselect_winner"),
]
