# Generated by Django 5.2.3 on 2026-06-13 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Заказчик'), ('supplier', 'Поставщик')], max_length=16)),
                ('company_name', models.CharField(max_length=200, verbose_name='Компания')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер')),
                ('category', models.CharField(choices=[('goods', 'Товары'), ('services', 'Услуги'), ('construction', 'Строительство'), ('it', 'ИТ и телеком'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к поставщику')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Место поставки')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начальная цена')),
                ('deadline', models.DateTimeField(verbose_name='Окончание приема заявок')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Прием заявок'), ('review', 'Рассмотрение'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена предложения')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='Срок поставки, дней')),
                ('warranty_months', models.PositiveIntegerField(default=0, verbose_name='Гарантия, месяцев')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('submitted', 'Подана'), ('winner', 'Победитель'), ('rejected', 'Не выбрана')], default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.tender')),
            ],
            options={
                'ordering': ['price', 'delivery_days'],
                'constraints': [models.UniqueConstraint(fields=('tender', 'supplier'), name='one_bid_per_supplier')],
            },
        ),
    ]
