# Generated by Django 5.2.3 on 2026-06-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_organization_tender_auction_step_tender_favorites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('preparation', 'Подготовка'), ('signed', 'Подписан'), ('completed', 'Исполнен'), ('terminated', 'Расторгнут')], default='preparation', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('inn__isnull', False), models.Q(('inn', ''), _negated=True)), fields=('inn',), name='unique_nonempty_organization_inn'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contracts', to='procurement.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_contracts', to='procurement.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='procurement.tender'),
        ),
        migrations.AddField(
            model_name='contract',
            name='winning_bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='procurement.bid'),
        ),
    ]
