# Generated by Django 5.2.3 on 2026-06-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_supplierdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На согласовании'), ('published', 'Прием заявок'), ('review', 'Рассмотрение'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=16, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TenderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='pending', max_length=16)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tender_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tender_approvals', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.tender')),
            ],
        ),
    ]
