# Generated by Django 5.2.3 on 2026-06-13 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_procurementprotocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена по лоту')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='Срок поставки, дней')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_offers', to='procurement.bid')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_offers', to='procurement.tenderlot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bid', 'lot'), name='one_offer_per_bid_lot')],
            },
        ),
    ]
