# Generated by Django 5.2.3 on 2026-06-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_bidlot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
    ]
