# Generated by Django 5.2.3 on 2026-06-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_contract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierapplication',
            options={'ordering': ['-submitted_at']},
        ),
    ]
