# Generated by Django 5.2.3 on 2026-06-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_scope_accreditation_to_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidlot',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_offers', to='procurement.tenderlot', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='tenderdocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'Всем участникам'), ('customer', 'Только заказчику')], default='public', max_length=16, verbose_name='Доступ'),
        ),
    ]
