# Generated by Django 5.2.3 on 2026-06-14 00:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_alter_bidlot_lot_alter_tenderdocument_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название источника')),
                ('url', models.URLField(max_length=500, verbose_name='URL JSON API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('items_path', models.CharField(blank=True, help_text='Например: result.items', max_length=120, verbose_name='Путь к списку')),
                ('auth_header', models.CharField(blank=True, help_text='Например: Authorization', max_length=80, verbose_name='Заголовок авторизации')),
                ('auth_env_var', models.CharField(blank=True, max_length=120, verbose_name='Переменная окружения с токеном')),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Например: {"external_id": "id", "title": "name", "deadline": "end_at"}', verbose_name='Соответствие полей')),
                ('status_mapping', models.JSONField(blank=True, default=dict, verbose_name='Соответствие статусов')),
                ('cancel_missing', models.BooleanField(default=False, help_text='Включайте только если API всегда возвращает полный список актуальных тендеров.', verbose_name='Отменять пропавшие тендеры')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_import_sources', to='procurement.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_import_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, verbose_name='ID во внешней системе')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на источник')),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_record', to='procurement.tender')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_tenders', to='procurement.tenderimportsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_tender_per_source')],
            },
        ),
    ]
