# Generated by Django 5.2.3 on 2026-06-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_tenderimportsource_importedtender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderimportsource',
            name='adapter',
            field=models.CharField(choices=[('json', 'Универсальный JSON API'), ('bidzaar', 'Bidzaar')], default='json', max_length=20, verbose_name='Адаптер'),
        ),
    ]
