# Generated by Django 5.2.3 on 2026-06-14 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_tenderlot_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TenderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('title', models.CharField(max_length=250, verbose_name='Название закупки')),
                ('category', models.CharField(choices=[('goods', 'Товары'), ('services', 'Услуги'), ('construction', 'Строительство'), ('it', 'ИТ и телеком'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к поставщику')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Место поставки')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Начальная цена')),
                ('procedure', models.CharField(choices=[('closed', 'Закрытый конкурс'), ('auction', 'Открытый аукцион')], max_length=16, verbose_name='Формат процедуры')),
                ('publish_results', models.BooleanField(default=True, verbose_name='Публиковать результаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_templates', to='procurement.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderTemplateLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название лота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Количество')),
                ('unit', models.CharField(default='шт.', max_length=30, verbose_name='Единица измерения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Начальная цена')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='procurement.tendertemplate')),
            ],
        ),
    ]
