# Generated by Django 5.2.3 on 2026-06-21 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_supplierdocument_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='pending_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_winner_for', to='procurement.bid', verbose_name='Предварительно выбранный победитель'),
        ),
        migrations.AddField(
            model_name='tender',
            name='winner_ranking_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Снимок рейтинга победителя'),
        ),
        migrations.AddField(
            model_name='tender',
            name='winner_selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата предварительного выбора'),
        ),
        migrations.AddField(
            model_name='tender',
            name='winner_selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preselected_tender_winners', to=settings.AUTH_USER_MODEL, verbose_name='Кем выбран победитель'),
        ),
    ]
