# Generated by Django 5.2.3 on 2026-06-22 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_tender_pending_winner_tender_winner_ranking_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.tender'),
        ),
        migrations.CreateModel(
            name='TenderWinnerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('ranking_snapshot', models.JSONField(blank=True, default=dict)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_selection', to='procurement.bid')),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_selections', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_selections', to='procurement.tender')),
            ],
            options={
                'ordering': ['selected_at'],
            },
        ),
        migrations.CreateModel(
            name='BidFraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shared_email', 'Одинаковый email'), ('shared_phone', 'Одинаковый телефон'), ('shared_address', 'Одинаковый юридический адрес'), ('shared_login_ip', 'Общий IP входа')], max_length=32)),
                ('value', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to='procurement.bid')),
                ('related_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_fraud_signals', to='procurement.bid')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to='procurement.tender')),
            ],
            options={
                'ordering': ['bid_id', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('bid', 'related_bid', 'kind'), name='unique_bid_fraud_signal')],
            },
        ),
    ]
