# Generated by Django 5.2.3 on 2026-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_alter_contract_tender_tenderwinnerselection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='bidfraudsignal',
            name='kind',
            field=models.CharField(choices=[('shared_email', 'Одинаковый email'), ('shared_phone', 'Одинаковый телефон'), ('shared_address', 'Одинаковый юридический адрес'), ('shared_login_ip', 'Общий IP входа'), ('shared_device_fingerprint', 'Совпадающий отпечаток устройства')], max_length=32),
        ),
    ]
